//
// Created by Vinicius on 29/11/2022.
//

#ifndef MEGABYTESTORE_PRODUCTTYPE_H
#define MEGABYTESTORE_PRODUCTTYPE_H

enum ProductType {CPUTYPE = 1, GPUTYPE, MOTHERBOARDTYPE, POWERSUPPLYTYPE, RAMMEMORYTYPE, STORAGEUNITTYPE};

#endif //MEGABYTESTORE_PRODUCTTYPE_H
